# Site settings
author: Paul Beckwith
title: Programming. As I Learn More...
header-img: img/home-bg.png
email: 303dog@gmail.com
copyright_name: Paul Beckwith
description: > # this means to ignore newlines until "baseurl:"
  Just jumping In!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  303dog

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
